Translate "npm audit: broken by design" into Japanese
gaearon/overreacted.io pull request #726
Opened 2021-07-22 16:03 UTC by fsubal

I translated "npm audit: broken by design" into Japanese.

2021-07-22 16:08 UTC, fsubal commented on src/pages/npm-audit-broken-by-design/index.ja.md
> +*注意: この記事は批判を含んでおり、また厭味ったらしい文体で書かれています。もちろん Node.js や npm のような巨大なプロジェクトをメンテナンスすることは大変な苦労であると理解してますし、間違いが明らかになるのに時間がかかるのも分かります。私はこの状況に対してフラストレーションを感じているのであって、関わった人々に何かを言うつもりはありません。それでもこういう書き方をしているのは当の
Tweet URL is wrong

```suggestion
*注意: この記事は批判を含んでおり、また厭味ったらしい文体で書かれています。もちろん Node.js や npm のような巨大なプロジェクトをメンテナンスすることは大変な苦労であると理解してますし、間違いが明らかになるのに時間がかかるのも分かります。私はこの状況に対してフラストレーションを感じているのであって、関わった人々に何かを言うつもりはありません。それでもこういう書き方をしているのは当のフラストレーションが年々悪化しており、この悲惨な状況を実際よりも小さく見せるようなマネはしたくなかったからです。私が特に見ていて辛いと感じるのはこれが初めてのプログラミングの体験になった人々、加えてまったく無関係の警告のせいでせっかくの変更をデプロイできなくなってしまった人々、みんなです。うれしいことに、[この問題について検討してくれる人が現れています](https://twitter.com/bitandbang/status/1412803378279759872)。解決策があがった際には私もできるだけ情報提供をしていきたいと思っています 💜*
```

2021-07-22 16:16 UTC, fsubal commented on src/pages/npm-audit-broken-by-design/index.ja.md
> +* **publish の過程ですべての依存をインライン化してしまう。** これは Create React App に近しいツールでこの頃見かけるようになった方法です。たとえば [Vite](https://unpkg.com/browse/vite@2.4.1/dist/node/) と [Next.js](https://unpkg.com/browse/next@11.0.1/dist/
typo

```suggestion
* **publish の過程ですべての依存をインライン化してしまう。** これは Create React App に近しいツールでこの頃見かけるようになった方法です。たとえば [Vite](https://unpkg.com/browse/vite@2.4.1/dist/node/) と [Next.js](https://unpkg.com/browse/next@11.0.1/dist/) はどちらも、自分の依存パッケージをそのままバンドルしています。npm が提供する `node_modules` の仕組みにそもそも頼っていません。メンテナから見れば、[これには明らかなメリットがあります](https://github.com/vitejs/vite/blob/main/.github/contributing.md#notes-on-dependencies)。起動時間が速くなり、ダウンロードサイズは小さくなり、そして ――すばらしいおまけとして―― ユーザーからの嘘の脆弱性報告を受け取らなくてすむようになるのです。これは仕組みの抜け穴をついたキレイな方法ですが、こういうインセンティブがエコシステムに生まれる原因は npm が作っており、私はそのことが心配になります。依存をインライン化したほうが良いというのは npm の目指すところに反してるとさえ言えるからです。
```

2021-07-22 16:16 UTC, fsubal commented on src/pages/npm-audit-broken-by-design/index.ja.md
> +初心者も、経験ある開発者も、メンテナ陣もセキュリティ担当部署も ―― そしてなによりすべてのユーザーが ―― もっとマシなものが相応しいです。
```suggestion
初心者も、経験ある開発者も、メンテナ陣もセキュリティ担当部署も ―― そしてなによりすべてのユーザーも ―― もっとマシなものを持つべきです。
```

2021-07-22 16:16 UTC, fsubal commented on src/pages/npm-audit-broken-by-design/index.ja.md
> +当面の間、私は `npm audit` に由来する GitHub の issue は、我々のプロジェクトに関係する _真の_ 脆弱性報告と呼べるものでない限り、今後すべて close するつもりです。他のメンテナたちにも同じポリシーで運用してもらおうと思っています。これは利用者のみなさんにとってはイライラの元になるかもしれませんが、そもそもの原因は npm にあるのです。このセキュリティ茶番劇に
```suggestion
当面の間、私は `npm audit` に由来する GitHub の issue は、我々のプロジェクトに関係する _真の_ 脆弱性報告と呼べるものでない限り、すべて close するつもりです。他のメンテナたちにも同じポリシーで運用してもらおうと思っています。これは利用者のみなさんにとってはイライラの元になるかもしれませんが、そもそもの原因は npm にあるのです。このセキュリティ茶番劇にはうんざりしました。問題を解決できるのは Node.js と npm しかいません。私からも連絡はしていきますが、対応の優先順位が上がることを祈るばかりです。
```

2021-07-22 16:16 UTC, fsubal commented on src/pages/npm-audit-broken-by-design/index.ja.md
> +* **脆弱性報告に反論する何らかの方法を提供する。** 当然ですが、この問題の全貌を Node.js や npm が把握しているわけではありません。いろんな人がいろんな提案を出している状況です。たとえば、この[プロポーザル](https://github.com/npm/rfcs/pull/18)では、audit の警告についてもう次から表示されないよう手動で解決できるようにしてはどうかと言っ
```suggestion
* **脆弱性報告に反論する何らかの方法を提供する。** 当然ですが、この問題の全貌を Node.js や npm が把握しているわけではありません。いろんな人がいろんな提案を出している状況です。たとえば、この[プロポーザル](https://github.com/npm/rfcs/pull/18)では、audit の警告について次回から表示しないように手動で解決できるようにしてはどうかと言っています。しかし、これでは結局ライブラリを利用する開発者たちの仕事は減りませんし、深いところにある依存について脆弱性報告が本物か偽物かを必ずしも判断できるわけではないでしょう。私が[提案](https://twitter.com/dan_abramov/status/1412380714012594178)したいのは、自分のライブラリを使っている人向けに、この脆弱性はうちには影響ないですよと知らせる方法があると良いというものです。もし、このライブラリ作者の判断が信じられないのだとしたら、なぜそのコードをあなたのコンピュータで動かしているんですか？これについては他の選択肢も議論したいと思ってます。
```

2021-07-22 16:26 UTC, fsubal commented on src/pages/npm-audit-broken-by-design/index.ja.md
> +
```suggestion
```

2021-07-22 16:27 UTC, yuheiy commented on src/pages/npm-audit-broken-by-design/index.ja.md
> +問題の根っこは npm はこれをデフォルトの挙動にしたことです。多くのシチュエーションで 99% 以上の確率で偽陽性に悩まされるようになり、初心者のプログラミング経験をとてつもなく混乱させ、人々をセキュリティ担当部署との折衝に向かわせ、ライブラリのもうメンテナにもう Node.js のエコシステムはこりごりだと思わせ、いずれは本当に悪い脆弱性が気づかれないまま出てしまう……そういう挙動を作ってし
```suggestion
問題の根っこは npm はこれをデフォルトの挙動にしたことです。多くのシチュエーションで 99% 以上の確率で偽陽性に悩まされるようになり、初心者のプログラミング経験をとてつもなく混乱させ、人々をセキュリティ担当部署との折衝に向かわせ、ライブラリのメンテナにもう Node.js のエコシステムはこりごりだと思わせ、いずれは本当に悪い脆弱性が気づかれないまま出てしまう……そういう挙動を作ってしまったことにあります。
```

2021-07-22 16:43 UTC, AumyF requested changes

2021-07-22 16:43 UTC, AumyF commented on src/pages/npm-audit-broken-by-design/index.ja.md
> +って待ってください。開発用サーバーというのは自分のコンピュータ上にあるものです。ファイルだって自分のです。ファイル監視の仕組みも *自分自身で* 書いた設定ファイルを使用しています。ここに出てくるロジックの、どの部分も自分のコンピュータから出ていませんね。もしこの攻撃者が、ローカル環境で開発している最中のあなたのコンピュータにログインできるほどの凄腕だとして、開発速度を落とすために特殊な長いファ
```suggestion
って待ってください。開発用サーバーというのは自分のコンピュータ上にあるものです。ファイルだって自分のです。ファイル監視の仕組みも *自分自身で* 書いた設定ファイルを使用しています。ここに出てくるロジックの、どの部分も自分のコンピュータから出ていませんね。もしこの攻撃者が、ローカル環境で開発している最中のあなたのコンピュータにログインできるほどの凄腕だとして、開発速度を落とすために特殊な長いファイルパスを作るなんて真似はしそうにありません。そうではなく、機密情報を盗みにくるでしょう。**この脅威全体がばかげた仮定と言わざるを得ません。**
```

2021-07-22 16:53 UTC, fsubal commented on src/pages/npm-audit-broken-by-design/index.ja.md
> +なんてこった、これはひどそうです！ **`npm audit` が真っ赤な文字を出してきやがりましたよ。**
`show it *in*` is better translated to "で"

```suggestion
なんてこった、これはひどそうです！ **`npm audit` が真っ赤な文字で出してきやがりましたよ。**
```

2021-07-22 17:22 UTC, fsubal commented on src/pages/npm-audit-broken-by-design/index.ja.md
> +深刻度「高」ですらこのアリサマですよ！
```suggestion
深刻度「高」とはなんだったんですか！
```

2021-07-26 18:48 UTC, ryota-murakami commented
@fsubal  ありがとうございます！
個人的な感想ですがタイトルは日本人的な感覚でも原文のカッコいい感じは分かると思うので、  
翻訳版である旨を記載する方法が良いのではないでしょうか？

**npm audit: broken by design** (日本語訳 

例えば[**TDD is dead**](https://dhh.dk/2014/tdd-is-dead-long-live-testing.html)は義務教育を受けた日本人なら意味も分かりますし、日本語にするより **TDD is dead** のままの方がカッコいいと感じる人が多いのではと思います。  
日本の会社も日本市場で出す作品に[**DEAD OR ALIVE**](https://www.amazon.co.jp/DEAD-OR-ALIVE-6-PS4/dp/B07H7H58KS)など英語のタイトルを付ける事はかなり日常的ですからね、それに抵抗を覚える人は殆ど居ないと思われます。

**設計から破綻しています**もタイトルとして相当インパクトが強いので良いと思いますが、  
日本語でも**デザイン**は頻繁に使う言葉ですし、日本人的な感覚だと**設計**は**Architecture**がまずに頭に浮かぶ人の方が多数派ではないかと思います、私の想像で引用出来る文元などはありませんが...
  
  　

何はともあれ忠実に翻訳して頂き本当にありがとうございます！
終わりの方に書いてあるビルドツールの類は `devDependency` に記載し `npm audit --production` オプションを付ける事で大半のFalse Positiveをサプレス出来るという知識はかなり有益と思われるのこの記事が日本で広く読まれるようになる事をとても嬉しく思います！ 🤗

--------------------------------------------------------------------

@gaearon I'm native Japanese person and I confirmed his translation is great, straightforward along to the original.  
I'm glad to that if the great post could reach many Japanese forks!

2021-08-28 15:25 UTC, fsubal commented
Sorry for the late response.

Remaining the original title like `npm audit: broken by design (Japanese edition)` only seems to make sense if the translation was reprinted in an external site ( like `This article is the translation of npm audit: broken by design in overreacted.io` ). 

Since overreacted.io links to translated versions in the same website, I don't think it has some good effect to avoiding  to translate the title into Japanese.

2021-08-28 15:45 UTC, fsubal commented
訳語について言いますと、タイトルで design を設計と訳すことを避けたい場合、本文中での「設計」という単語も変えたほうが良いということになりそうですが、この点についてはどう思いますか？ @ryota-murakami

2021-08-29 03:06 UTC, ryota-murakami commented
@fsubal どちらでも大丈夫だと思います😀

2023-11-06 02:41 UTC, closed without merging